### ISSUE TITLE
Hello, can you add a bit of documentation on how the graph should be represented?

### ISSUE THREAD

**Issue by ksrinivs64** [jwzhanggy/Graph-Bert#1]
I noticed that you assume everything is stored as numpy matrices already.  Is there a pointer to how graphs are represented in the node and links files (is links just a sparse adjacency list and node a set of features)?  Thanks!

**Comment by jwzhanggy** [comment]
A new readme.tex file is uploaded on your questions. Please refer to ./data/cora/README.tex for more information.
