### ISSUE TITLE
Graph representation of custom dataset and ASTs

### ISSUE THREAD

**Issue by m-jojo-s** [jwzhanggy/Graph-Bert#10]
The given cora example makes nodes from papers and has links between each node (paper). However, my dataset has a bunch of text files and my graph is focused on each individual text file rather than dependency of one file to another and the order of tokens/features within each file is important as well. I have an AST graph of each text file but I'm unsure of how I can represent it for input to Graph-Bert. 
If I make nodes out of each line of text, the feature vectors will be too sparse for each node and the number of nodes will be extremely large. If I make nodes on each text file, the structure and dependency within each file will be lost and I am unsure of what the links will be then. 

If there's a way to represent this for input to Graph-Bert, please let me know. Thank you.

**Comment by jwzhanggy** [comment]
Please see another graph-bert paper instead, which may work for your problem.

https://github.com/jwzhanggy/SEG-BERT

**Comment by m-jojo-s** [comment]
Thank you!
