### ISSUE TITLE
[Question] Position-Embed function Eqn. 3

### ISSUE THREAD

**Issue by vijaydwivedi75** [jwzhanggy/Graph-Bert#13]
Hi, 
Thanks for the great work and the source codes!

I was wondering whether the Eqn 3 from the paper is implemented in the codes? I could not find them, and notice that the position features are directly passed to `nn.Embedding()`?

https://github.com/jwzhanggy/Graph-Bert/blob/e87857698b6cb97ca67479da5d3c512d2ecf9e68/code/MethodBertComp.py#L99-L104

https://github.com/jwzhanggy/Graph-Bert/blob/e87857698b6cb97ca67479da5d3c512d2ecf9e68/code/MethodBertComp.py#L109-L114

Thanks,
Vijay

**Comment by jwzhanggy** [comment]
Yes, in the code, we decide to follow the BERT code and use nn.embedding for encoding the positions.

**Comment by vijaydwivedi75** [comment]
Thanks a lot for your super-quick response, @jwzhanggy!

Sorry to re-confirm: 
so the Eqn. 3 (the Position-Embed function with sine and cosine) is not used, correct?
