### ISSUE TITLE
Running script_2_pre_train for Node Attribute Reconstruction and Graph Bert Network Structure Recovery

### ISSUE THREAD

**Issue by lilaspourpre** [jwzhanggy/Graph-Bert#20]
Hi! Your paper states that:
"In the experiments, we first pre-train GRAPH-BERT based on
the node attribute reconstruction task with 200 epochs, then
load and pre-train the same GRAPH-BERT model again based
on the graph structure recovery task with another 200 epochs."

However, script_2_pre_train.py learns two different models. Could you please specify, whether you applied those models separately for the downstream task? 

If your paper is describing the workflow correctly, what should I do to train one model on both tasks?

Thank you in advance for the answer.
Yours sincerely,
Irina Nikishina.

**Comment by zfallahnejad** [comment]
I have the same question. It seems that `script_2_pre_train.py` not only trains two different models, but also does not save these models anywhere after training.
