### ISSUE TITLE
About the size of the input graph

### ISSUE THREAD

**Issue by code-gamer** [jwzhanggy/Graph-Bert#23]
Although you said that your method support large size graph in your paper, I tested it on a graph with about 10, 000 nodes, the program was terminated while running because it exceeded the system memory. However, the memory of the server is 128G，so where might the problem lie?

**Comment by jwzhanggy** [comment]
you can change the code to use mini-batch instead

**Comment by code-gamer** [comment]
> you can change the code to use mini-batch instead

Thanks for your reply, I'll try first.

**Comment by code-gamer** [comment]
> you can change the code to use mini-batch instead
Sorry to bother you again. This issue happened when I try to use DatasetLoader.py to generate intimacy matrix "S", but isn’t mini-batch used in the model training process?
