### ISSUE TITLE
Is it possible to apply your GRAPH-BERT on directed graphs ? 

### ISSUE THREAD

**Issue by dproxy8** [jwzhanggy/Graph-Bert#3]
Hi,
I'm wondering if it's possible to GRAPH-BERT on directed graphs.

Thank you.

**Comment by jwzhanggy** [comment]
Hi,

It should be OK go apply Graph-Bert on directed graphs, but necessary extensions can be needed to learn both nodes' in- and out-representations with considerations about the link directions. You can also refer to our recent paper on directed graph embeddings attached as follows, similar ideas can be used to extend Graph-Bert for directed graph settings. 

Collective Link Prediction Oriented Network Embedding with Hierarchical Graph Attention
https://arxiv.org/pdf/1910.05736.pdf

Best,
Jiawei

**Comment by dproxy8** [comment]
Thank you for the answer and the description!
