### ISSUE TITLE
question about the linkless subgraphs sampling

### ISSUE THREAD

**Issue by dproxy8** [jwzhanggy/Graph-Bert#7]
Hi, 
In your graph-bert, you calculate the intimacy matrix in step 1, then sample linkless subgraphs and embed nodes in step 2.  In the process of sampling linkless subgraphs, nodes of the linkless subgraphs are sorted based on the intimacy scores.

The question is, is it possible to change this sampling method to something else? (e.g., [ripple walk sampling algorithm](https://arxiv.org/abs/2002.07206). I know this is one of your great works.) 
If yes, how and where should I rewrite this codes to implement that?

Thank you in advance.

**Comment by jwzhanggy** [comment]
Hi,

Just want to clarify that we didn't do intimacy matrix calculation in step 1... In the step 1, we calculate the WL code of nodes.

If you plan to use different sampling algorithm, you just need to re-implement step 2 in the pre-processing script with your own sampling approach. You can rewrite "MethodGraphBatching.py" with your own sampling class instead. Just FYI.

Best,
Jiawei
