### ISSUE TITLE
[question] Weight Loading

### ISSUE THREAD

**Issue by MohsenFazaeli** [jwzhanggy/Graph-Bert#8]
Hi,

I have a question where fine-tune script loads the pre-trained weight files?

**Comment by jwzhanggy** [comment]
Please refer to the attached page for model save/load in pytorch:
https://pytorch.org/tutorials/beginner/saving_loading_models.html

You can load the pre-trained graph-bert component with pytorch model (e.g., the graph-bert inside MethodGraphBertNodeClassification) with the save and load functions in the above page. According to our experiments, Save/Load Entire Model in the above page works perfectly, whereas Save/Load state_dict doesn't really work.
