### ISSUE TITLE
Some questions about intimacy matrix

### ISSUE THREAD

**Issue by ZhuYun97** [jwzhanggy/Graph-Bert#9]
I have some questions while reading the paper of Graph-BERT. What does the intimacy score mean? What the difference between intimacy score and similarity score? When I try to understand the intimacy matrix, I find the nearest neighbors will get the highest intimacy score(e.g. 1-hop neighbors always get the highest intimacy score). Why does the context nodes can cover both local neighbors as well as the nodes which are far away. 

Could you please help figure out these problems? Thanks for your help!

**Comment by jwzhanggy** [comment]
That should be something basic. You can search for some papers/tutorials on PageRank or Random Walk or Markov Chain to get some ideas on that matrix.
